use_frameworks!

platform :ios, '8.0'

target 'FirstLineHeadIndentAnimation_Example' do
  pod 'FirstLineHeadIndentAnimation', :path => '../'

  target 'FirstLineHeadIndentAnimation_Tests' do
    inherit! :search_paths

    
  end
end
