source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'FirstLineHeadIndentAnimation_Example' do

  pod 'JPBasic'
  pod 'YYWebImage'
  pod 'MJRefresh'
  pod 'MJExtension'
  
  target 'FirstLineHeadIndentAnimation_Tests' do
    inherit! :search_paths

    
  end
end
